version: '2'
services:

  ldapserver:
    image: 'teradatalabs/centos6-java8-oracle-openldap:${DOCKER_IMAGES_VERSION}'

  presto-master:
    domainname: docker.cluster
    hostname: presto-master
    image: 'teradatalabs/centos6-java8-oracle-ldap:${DOCKER_IMAGES_VERSION}'
    command: /docker/volumes/conf/docker/files/presto-launcher-wrapper.sh multinode-tls-ldap-master run
    ports:
      - '7778:7778'
    networks:
      default:
        aliases:
         - presto-master.docker.cluster
    depends_on:
      - ldapserver

  presto-worker-1:
    domainname: docker.cluster
    hostname: presto-worker-1
    extends:
      file: ../common/standard.yml
      service: java-8-base
    image: 'teradatalabs/centos6-java8-oracle-ldap:${DOCKER_IMAGES_VERSION}'
    command: /docker/volumes/conf/docker/files/presto-launcher-wrapper.sh multinode-tls-ldap-worker run
    networks:
      default:
        aliases:
         - presto-worker-1.docker.cluster
    depends_on:
      - presto-master
    volumes_from:
      - presto-master

  presto-worker-2:
    domainname: docker.cluster
    hostname: presto-worker-2
    extends:
      file: ../common/standard.yml
      service: java-8-base
    image: 'teradatalabs/centos6-java8-oracle-ldap:${DOCKER_IMAGES_VERSION}'
    command: /docker/volumes/conf/docker/files/presto-launcher-wrapper.sh multinode-tls-ldap-worker run
    networks:
      default:
        aliases:
         - presto-worker-2.docker.cluster
    depends_on:
      - presto-master
    volumes_from:
      - presto-master

  application-runner:
    image: 'teradatalabs/centos6-java8-oracle-ldap:${DOCKER_IMAGES_VERSION}'
    volumes:
      - ../../../conf/tempto/tempto-configuration-for-docker-tls-ldap.yaml:/docker/volumes/tempto/tempto-configuration-local.yaml
